version: "3"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: varchas-server
    container_name: django
    restart: unless-stopped
    env_file: .env
    environment:
      # - DB_HOST=postgresqldb
      - CHOKIDAR_USEPOLLING=true
      - EMAIL_USE_TLS=True
    ports:
      - 8888:8888
    volumes:
      - .:/app
    # depends_on:
    #   - postgresqldb
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations main
        python manage.py makemigrations accounts
        python manage.py makemigrations adminportal
        python manage.py makemigrations events
        python manage.py makemigrations registration
        python manage.py makemigrations sponsors
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8888
        
  # postgresqldb:
  #   image: "bitnami/postgresql:latest"
  #   container_name: postgresqldb
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - POSTGRESQL_USERNAME=$DB_USER
  #     - POSTGRESQL_PASSWORD=$DB_PASSWORD
  #     - POSTGRESQL_DATABASE=$DB_NAME
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - dbdata:/bitnami/postgresql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
